### ISSUE TITLE
Display readable size and add date

### ISSUE THREAD

**Issue by hbooo** [nurzico/transmission-web-control#2]
Hi, 

Currently size are displayed like this : 
![image](https://user-images.githubusercontent.com/242125/68289865-364fb600-0087-11ea-9f9a-9eb59a4ea978.png)
and dates like this : 
![image](https://user-images.githubusercontent.com/242125/68289887-44053b80-0087-11ea-90e1-2b972d685079.png)
it's pretty to hard to know what is the information.

A formated date and size would help a lot

**Comment by nurzico** [comment]
Can you check whether any js file not loaded? This part is working under base theme. So no issue.

**Comment by hbooo** [comment]
I have these errors in the chrome console 
![image](https://user-images.githubusercontent.com/242125/68398433-054daf00-0175-11ea-8794-7c2ade5c386f.png)

I only have the second one on ronggang's version but dates and sizes are displayed correctly

**Comment by nurzico** [comment]
I am not sure about the js file you mentioned. But it is not loaded from two of the base html file here. I think you have got some conflicts!
Try to fresh install the theme. And don't forget to clear browser cache!
